version: '3.7'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  timescale:
    image: timescale/timescaledb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
